### ISSUE TITLE
riot-desktop 1.6.0-1 for debian stretch was compiled against glibc 2.27

### ISSUE THREAD

**Issue by ollieparanoid** [vector-im/riot-builder#24] opened 2020-05-09 10:37 UTC
Debian stretch is on glibc 2.24: https://packages.debian.org/stretch/glibc-source

Riot desktop is segfaulting there, seems like the reason is that it was compiled against GLIBC_2.27:
```
$ riot-desktop 
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
Seshat unexpected error: Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /tmp/.org.chromium.Chromium.kU3VUq)
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
Starting auto update with base URL: https://packages.riot.im/desktop/update/
Auto update not supported on this platform
Segmentation fault
```

```
$ apt show riot-desktop
Package: riot-desktop
Version: 1.6.0-1
Priority: extra
Section: net
Maintainer: support@riot.im
Installed-Size: unknown
Provides: riot-web
Depends: libgtk-3-0, libnotify4, libnss3, libxss1, libxtst6, xdg-utils, libatspi2.0-0, libuuid1, libappindicator3-1, libsecret-1-0, libsqlcipher0
Replaces: riot-web
Homepage: https://riot.im/
License: Apache-2.0
Vendor: support@riot.im
Download-Size: 61.4 MB
APT-Manual-Installed: no
APT-Sources: https://riot.im/packages/debian stretch/main amd64 Packages
Description: A feature-rich client for Matrix.org
```

I'll just switch the VM I'm running riot in to a newer debian release, but possibly there are users who are on stretch and can't simply switch.

**Comment by t3chguy** [comment] 2020-05-09 11:07
Duplicate of https://github.com/vector-im/riot-web/issues/13553

**Closed by t3chguy** 2020-05-09 11:07 UTC
